language: cpp
sudo: required
dist: bionic
compiler: gcc
branches:
  only:
    - master
    - "2.0"
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: ANALYZE="scan-build-3.9 -o out " GH_REF=github.com/LibreCAD/static-analyzer-reports.git
  allow_failures:
  - env: ANALYZE="scan-build-3.9 -o out " GH_REF=github.com/LibreCAD/static-analyzer-reports.git
install:
- sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.6-bionic
- sudo apt-get -y update
- sudo apt-get -qq install qt512-meta-full libgl-dev libmuparser-dev libboost-dev libfreetype6-dev libicu-dev pkg-config
- |
  if [ "${ANALYZE}" ]; then
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;
    echo "yes" | sudo apt-add-repository "deb http://llvm.org/apt/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-3.9 main";
    sudo apt-get update;
    sudo apt-get -qq install clang-3.9;
  fi;
script:
- source /opt/qt512/bin/qt512-env.sh
- ${ANALYZE}qmake -r librecad.pro CONFIG+=debug_and_release
- ${ANALYZE}make debug -j2
- if [ "${ANALYZE}" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./CI/static-analyzer-reports.sh; fi
